---
# Enable logging
logger:
# Remember to disable logger if using the primary UART! Override in device's yaml by
# duplicating this and uncommenting below.
#  baud_rate: 0 #disable UART logging
#  level: INFO # reduce from default of debug, override in device if needed (https://esphome.io/components/logger/#log-levels)
